site_name: Curso OpenShift

theme:
  name: material
  language: es

  features:
    - content.code.copy
    - navigation.top

nav:
  - Inicio: index.md

  - Sesión 1:
      - 1.1 Introducción: sesion1/1.1 Introduccion.md
      - 1.2 De servidor a contenedor: sesion1/1.2 de servidor a contendor.md
      - 1.3 Kubernetes: sesion1/1.3 kubernetes.md
      - 1.4 Qué añade OpenShift: sesion1/1.4 que añade openshift.md
      - 1.5 Arquitectura del clúster: sesion1/1.5 Arquitectura cluster.md
      - 1.6 Consola web: sesion1/1.6 Consola web.md
      - 1.7 Cliente oc: sesion1/1.7 cliente oc.md
      - 1.8 Práctica: sesion1/1.8-practica-imagen-cluster-completo.md
      - 1.9 Cierre: sesion1/1.9 cierre.md

  - Sesión 2:
      - 2.1 Cargas de trabajo: sesion2/2.1 Cargas de trabajo.md
      - 2.2 Exponer aplicaciones: sesion2/2.2 Exponer aplicaciones.md
      - 2.2 2.3 Salud recursos y escalado: sesion2/2.2 2.3 Salud recursos y escalado.md
      

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
